name: Hackathon Evaluation

on:
  pull_request:
    branches:
      - main

jobs:
  evaluate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Decode evaluation script from base64 secret
      - name: Decode and write evaluation script
        run: |
          echo "${{ secrets.EVALUATION_SCRIPT_B64 }}" | base64 -d > evaluation.py

      # Decode target.txt from base64 secret
      - name: Create target.txt from secret
        run: |
          echo "${{ secrets.TARGET_FILE_B64 }}" | base64 -d > target.txt

      # Run the evaluation using the target and the attempted file (from PR)
      - name: Run evaluation script
        run: |
          # Check if submission.txt exist before running the script
          if [[ -f submission/submission.txt ]]; then
            python evaluation.py target.txt submission/submission.txt
          else
            echo "submission/submission.txt file are missing. Skipping evaluation."
            exit 0  # Exit without error
          fi

      # Cleanup
      - name: Delete sensitive files
        run: |
          rm -f evaluation.py target.txt